#!/usr/bin/env python3
"""Sort a parsed diff into signal and noise, and decide what the model may read.

Two jobs, both deterministic. First: label every file from its path, its shape,
and its own content - generated, vendored, a lockfile, a test, formatting only.
Second: spend a byte budget on the hunks worth spending it on, so a 40-file
refactor arrives as the eight files that carry the change plus honest counts for
the other thirty-two.

Everything here is a *hint*. The analysis phase can and does disagree: a one-line
change in a generated client is mechanical, but a one-line change in a lockfile
that moves a major version is not, and only a reader can tell those apart. What
this script guarantees is that the disagreement starts from the same facts every
time, and that every non-obvious call carries a reason a human can audit.

Usage:
    python3 classify.py pre_model.json [-o classified.json]
    python3 parse_diff.py change.diff | python3 classify.py -

Exits 0 when the document was classified, 1 when it is not a pre-model.
"""
from __future__ import annotations

import argparse
import json
import re
import sys

# Past this much hunk text the mechanical files start getting summarised rather
# than quoted. Sized so that a large but ordinary PR still arrives whole.
DEFAULT_MAX_BYTES = 200_000

ROLES = {"api", "domain", "persistence", "tests", "config", "generated",
         "docs", "build", "infra", "ui", "other"}

LOCKFILES = {
    "package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml",
    "bun.lockb", "poetry.lock", "pipfile.lock", "uv.lock", "pdm.lock",
    "cargo.lock", "composer.lock", "gemfile.lock", "go.sum", "mix.lock",
    "packages.lock.json", "gradle.lockfile", "flake.lock", "pubspec.lock",
    "conda-lock.yml", "requirements.txt.lock", "deno.lock",
}

VENDORED_DIRS = ("vendor/", "third_party/", "thirdparty/", "node_modules/",
                 "bower_components/", "godeps/", "pods/", ".yarn/",
                 "site-packages/", "external/deps/")

GENERATED_DIRS = ("generated/", "gen/", "__generated__/", "dist/", ".next/",
                  "__pycache__/", "target/generated-sources/", "coverage/")

GENERATED_NAMES = re.compile(
    r"(_pb2(_grpc)?\.pyi?|\.pb\.go|\.pb\.cc|\.pb\.h|_generated\.go|\.g\.dart"
    r"|\.freezed\.dart|\.designer\.cs|\.min\.js|\.min\.css|\.map"
    r"|_pb\.js|_pb\.d\.ts|\.generated\.[a-z]+)$", re.I)

# Generators are loud about it. This is the marker convention they share.
GENERATED_MARKER = re.compile(
    r"@generated\b|DO NOT EDIT|Code generated by|autogenerated|auto-generated"
    r"|This file was automatically generated|@?generated by", re.I)

TEST_PATTERNS = re.compile(
    r"(^|/)(tests?|specs?|__tests__|testdata|fixtures)(/|$)"
    r"|(^|/)(test_[^/]+|conftest)\.py$"
    r"|[._-]test\.[a-z]+$|[._-]spec\.[a-z]+$|_test\.(go|py|rb|exs?)$"
    r"|Test[s]?\.(java|kt|cs|scala)$", re.I)

DOC_PATTERNS = re.compile(
    r"(^|/)(docs?|documentation|adr|rfcs?)(/|$)"
    r"|(^|/)(readme|changelog|contributing|license|licence|notice|authors|"
    r"code_of_conduct|security)(\.[a-z]+)?$"
    r"|\.(md|mdx|rst|adoc|txt)$", re.I)

BUILD_PATTERNS = re.compile(
    r"(^|/)\.github/|(^|/)\.gitlab-ci\.yml$|(^|/)\.circleci/"
    r"|(^|/)(makefile|gnumakefile|justfile|rakefile|dockerfile[^/]*|"
    r"containerfile|jenkinsfile|procfile|\.dockerignore|\.gitignore|"
    r"\.gitattributes|\.editorconfig|\.pre-commit-config\.yaml)$"
    r"|(^|/)(package\.json|pyproject\.toml|setup\.(py|cfg)|requirements[^/]*\.txt|"
    r"cargo\.toml|go\.mod|gemfile|build\.gradle[^/]*|pom\.xml|"
    r"tsconfig[^/]*\.json|vite\.config\.[a-z]+|webpack\.config\.[a-z]+|"
    r"rollup\.config\.[a-z]+|babel\.config\.[a-z]+|jest\.config\.[a-z]+|"
    r"\.eslintrc[^/]*|\.prettierrc[^/]*|tox\.ini|noxfile\.py)$"
    r"|(^|/)scripts?/", re.I)

INFRA_PATTERNS = re.compile(
    r"\.tf(vars)?$|(^|/)(terraform|k8s|kubernetes|helm|charts?|ansible|"
    r"deploy(ment)?s?|infra(structure)?|manifests)(/|$)"
    r"|(^|/)docker-compose[^/]*\.ya?ml$", re.I)

PERSISTENCE_PATTERNS = re.compile(
    r"\.sql$|(^|/)(migrations?|alembic|schema|db|database|repositories|"
    r"repository|dao|entities|models?|stores?)(/|$)"
    r"|(^|/)(models?|schema|repository)\.[a-z]+$", re.I)

API_PATTERNS = re.compile(
    r"(^|/)(api|apis|routes?|routers?|controllers?|handlers?|endpoints?|"
    r"resolvers?|serializers?|views?)(/|$)"
    r"|(^|/)(urls|views|routes|schema)\.py$|\.proto$|\.graphql$|\.gql$"
    r"|openapi[^/]*\.(ya?ml|json)$|swagger[^/]*\.(ya?ml|json)$", re.I)

UI_PATTERNS = re.compile(
    r"(^|/)(components?|pages|screens|views|widgets|templates|styles|assets|"
    r"public|static)(/|$)"
    r"|\.(tsx|jsx|vue|svelte|css|scss|sass|less|html)$", re.I)

CONFIG_PATTERNS = re.compile(
    r"(^|/)(config|configs|conf|settings|env)(/|$)"
    r"|\.(ya?ml|toml|ini|cfg|conf|properties|env)$"
    r"|(^|/)\.env(\.[a-z]+)?$", re.I)

CODE_LANGUAGES = {
    "python", "ruby", "go", "rust", "javascript", "typescript", "java",
    "kotlin", "scala", "swift", "objectivec", "c", "cpp", "csharp", "php",
    "perl", "elixir", "erlang", "haskell", "clojure", "dart", "lua", "r",
    "solidity", "bash", "fish", "groovy", "zig",
}

MECHANICAL, SUPPORTING, CORE = "mechanical", "supporting", "core"


# --------------------------------------------------------------- shape

def _changed(hunks: list[dict]) -> tuple[list[str], list[str]]:
    added = [l["c"] for h in hunks for l in h["lines"] if l["t"] == "+"]
    removed = [l["c"] for h in hunks for l in h["lines"] if l["t"] == "-"]
    return added, removed


def _bare(line: str) -> str:
    return re.sub(r"\s+", "", line)


def whitespace_only(added: list[str], removed: list[str]) -> bool:
    """Same lines in the same order, differing only in their whitespace."""
    if not added or len(added) != len(removed):
        return False
    return all(_bare(a) == _bare(r) for a, r in zip(added, removed)) and added != removed


def formatting_only(added: list[str], removed: list[str]) -> bool:
    """Same text once every space is removed, even if it was rewrapped.

    A formatter that splits one call across four lines changes the line count,
    so this compares the blob rather than the lines. It is the looser of the two
    and whitespace-only changes satisfy it as well.
    """
    if not added or not removed:
        return False
    return "".join(_bare(l) for l in added) == "".join(_bare(l) for l in removed)


def line_endings_changed(added: list[str], removed: list[str]) -> bool:
    return (any(l.endswith("\r") for l in added) !=
            any(l.endswith("\r") for l in removed))


# --------------------------------------------------------------- labels

def classify_file(file: dict, hunks: dict) -> dict:
    """Everything this script knows about one file, and why it thinks so."""
    path = (file["path"] or file["old_path"] or "").strip()
    name = path.rsplit("/", 1)[-1].lower()
    lower = path.lower()
    own = [hunks[h] for h in file["hunk_ids"] if h in hunks]
    added, removed = _changed(own)
    reasons: list[str] = []

    lockfile = name in LOCKFILES
    if lockfile:
        reasons.append("%s is a lockfile" % name)

    vendored = any(d in lower + "/" for d in VENDORED_DIRS)
    if vendored:
        reasons.append("path is under a vendored directory")

    generated = False
    if GENERATED_NAMES.search(name):
        generated = True
        reasons.append("filename matches a generator's output convention")
    elif any(("/" + d) in ("/" + lower + "/") for d in GENERATED_DIRS):
        generated = True
        reasons.append("path is under a generated-output directory")
    else:
        # The file says so itself. Only the first lines of what was actually
        # read are checked, which is where every generator puts its banner.
        head = [l["c"] for h in own for l in h["lines"][:12]][:24]
        marker = next((l for l in head if GENERATED_MARKER.search(l)), None)
        if marker is not None:
            generated = True
            reasons.append("file header says %r" % marker.strip()[:48])

    test = bool(TEST_PATTERNS.search(path))
    if test:
        reasons.append("path follows a test convention")

    ws_only = whitespace_only(added, removed)
    fmt_only = ws_only or formatting_only(added, removed)
    if ws_only:
        if line_endings_changed(added, removed):
            reasons.append("line endings changed; nothing else did")
        else:
            reasons.append("every changed line differs only in whitespace")
    elif fmt_only:
        reasons.append("the text is identical once whitespace is ignored")

    if file["is_binary"]:
        reasons.append("binary; there is no text to read")
    if file["status"] == "mode_changed":
        reasons.append("only the file mode changed")
    if file["status"] == "renamed" and not own:
        reasons.append("renamed with no edits")
    elif file["status"] == "renamed":
        reasons.append("renamed from %s with edits" % file["old_path"])

    role = _role_of(file, path, lower, name, generated, vendored, lockfile, test)
    hint = _hint_of(file, role, generated, vendored, lockfile, fmt_only, own)

    if hint == MECHANICAL and not reasons:
        # The contract: nothing is dismissed without a stated reason.
        reasons.append("%s files are read as context, not as the change" % role)

    return {
        "role": role,
        "generated": generated,
        "vendored": vendored,
        "lockfile": lockfile,
        "test": test,
        "formatting_only": fmt_only,
        "whitespace_only": ws_only,
        "significance_hint": hint,
        "reasons": reasons,
    }


def _role_of(file, path, lower, name, generated, vendored, lockfile, test) -> str:
    """First match wins, so the order is the ranking of what a path tells you."""
    if generated or vendored:
        return "generated"
    if lockfile:
        return "build"
    if test:
        return "tests"
    if DOC_PATTERNS.search(path):
        return "docs"
    if BUILD_PATTERNS.search(path):
        return "build"
    if INFRA_PATTERNS.search(path):
        return "infra"
    if PERSISTENCE_PATTERNS.search(path):
        return "persistence"
    if API_PATTERNS.search(path):
        return "api"
    if UI_PATTERNS.search(path):
        return "ui"
    if CONFIG_PATTERNS.search(path):
        return "config"
    if file.get("language") in ("bash", "fish"):
        # Shell in a repository is tooling far more often than it is the
        # product. Supporting, so it is still read, just not read first.
        return "build"
    if file.get("language") in CODE_LANGUAGES:
        return "domain"
    return "other"


def _hint_of(file, role, generated, vendored, lockfile, fmt_only, own) -> str:
    if generated or vendored or lockfile or fmt_only or file["is_binary"]:
        return MECHANICAL
    if file["status"] == "mode_changed":
        return MECHANICAL
    if file["status"] == "renamed" and not own:
        return MECHANICAL
    if role in ("tests", "docs", "config", "build", "infra", "other"):
        return SUPPORTING
    return CORE


# --------------------------------------------------------------- budget

def apply_budget(model: dict, max_bytes: int) -> dict:
    """Elide hunk bodies, cheapest signal first, until the diff fits.

    Nothing is dropped: an elided hunk keeps its header, its counts, and its
    place in the file. The report can still say what changed there, it just
    cannot quote it, and `coverage` says so on the page.
    """
    hint_by_hunk = {}
    for file in model["files"]:
        hint = file["classification"]["significance_hint"]
        for hid in file["hunk_ids"]:
            hint_by_hunk[hid] = hint

    def size(hunk):
        return sum(len(l["c"]) + 1 for l in hunk["lines"])

    total = sum(size(h) for h in model["hunks"].values())
    elided_hints = set()
    if total > max_bytes:
        # Biggest first within a tier: eliding one lockfile hunk buys more than
        # twenty small ones and costs the reader less.
        for hint in (MECHANICAL, SUPPORTING, CORE):
            order = sorted(
                (h for h in model["hunks"].values()
                 if hint_by_hunk.get(h["id"]) == hint and not h["elided"]),
                key=size, reverse=True)
            for hunk in order:
                if total <= max_bytes:
                    break
                total -= size(hunk)
                hunk["lines"] = []
                hunk["elided"] = True
                elided_hints.add(hint)
            if total <= max_bytes:
                break

    elided = [h for h in model["hunks"].values() if h["elided"]]
    if not elided:
        tier = "full"
    elif elided_hints <= {MECHANICAL}:
        tier = "core"
    else:
        tier = "summary"

    model["budget"].update({
        "tier": tier,
        "max_bytes": max_bytes,
        "hunks_total": len(model["hunks"]),
        "hunks_included": len(model["hunks"]) - len(elided),
        "hunks_elided": len(elided),
        "bytes_included": total,
    })
    if elided:
        model["warnings"].append(
            "%d of %d hunks were summarised rather than quoted to stay inside "
            "the %d character budget." % (len(elided), len(model["hunks"]), max_bytes))
    return model


def classify(model: dict, max_bytes: int = DEFAULT_MAX_BYTES) -> dict:
    hunks = model["hunks"]
    by_role: dict[str, int] = {}
    for file in model["files"]:
        file["classification"] = classify_file(file, hunks)
        role = file["classification"]["role"]
        by_role[role] = by_role.get(role, 0) + file["additions"] + file["deletions"]
    model["stats"]["changed_lines_by_role"] = dict(sorted(by_role.items()))
    return apply_budget(model, max_bytes)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("pre_model", help="parse_diff.py output, or - for stdin")
    ap.add_argument("-o", "--out", help="write here instead of stdout")
    ap.add_argument("--max-bytes", type=int, default=DEFAULT_MAX_BYTES,
                    help="hunk text the analysis phase may be handed "
                         "(default %d)" % DEFAULT_MAX_BYTES)
    ap.add_argument("--compact", action="store_true")
    args = ap.parse_args(argv)

    raw = sys.stdin.read() if args.pre_model == "-" else \
        open(args.pre_model, encoding="utf-8").read()
    try:
        model = json.loads(raw)
    except json.JSONDecodeError as exc:
        sys.stderr.write("classify: not JSON: %s\n" % exc)
        return 1
    if not isinstance(model, dict) or "files" not in model or "hunks" not in model:
        sys.stderr.write("classify: this is not a pre-model; run parse_diff.py first\n")
        return 1

    model = classify(model, args.max_bytes)
    text = json.dumps(model, indent=None if args.compact else 2,
                      ensure_ascii=False, sort_keys=False)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(text + "\n")
        print(args.out)
    else:
        sys.stdout.write(text + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
